---
title: "Welcome to Shamindra’s Site"
description: |
  Detailing interesting things in the life of a PhD statistics
  student at CMU
categories:
  - personal
author:
  - name: Shamindra Shrotriya
    url: https://www.shamindras.com/
date: 07-10-2019
preview: images/about-profile-circular-scaled-50.png
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(emo) # For emoji's
```

## Welcome - Let's Get Statistical!

Hi there! I’m **Shamindra Shrotriya**, a graduate student in the [Department of Statistics and Data Science](http://www.stat.cmu.edu/){target="_blank"} at the
wonderful [Carnegie Mellon University](https://www.cmu.edu/){target="_blank"}. I’ve decided to start 
blogging to document my learning and development in statistics as a 
graduate student.

I’d like it to be a fun place to document interesting things I like to 
read about in the statistics and machine learning space (`statistical theory/methodology research`, `rstats`, `python` etc) as well as anything else I am generally into e.g. books, sports.

Feel free to pull up a chair, leave a comment, and join me 
so that we can explore together `r emo::ji("100")`.

## Credits

The credit to starting this blog goes to the following people. I
hope to not disappoint and create some useful content here `r emo::ji("vulcan_salute")`.

- [Yihui Xie](https://yihui.name/){target="_blank"}, [JJ Allaire](https://github.com/jjallaire){target="_blank"} and [Rich Iannone](https://twitter.com/riannone){target="_blank"} - for co-developing the fantastic `radix` package which upon which this blog/ site is based
- [Rachel Thomas](http://www.fast.ai/) for posting this [fantastic blog post](http://www.fast.ai/2017/04/06/alternatives/){target="_blank"} encouraging people like me to (finally!) create a blog
- My parents for encouraging to communicate my passion for Statistics.
I secretly think that this is their way of minimizing my passionate
rants about the bootstrap in our Skype chats. That will still continue though `r emo::ji("smile")`

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://twitter.com/shamindraas" target="_blank" class="fa fa-twitter" style="font-size:36px;"></a>
    <a href="https://www.linkedin.com/in/shamindras/" target="_blank" class="fa fa-linkedin" style="font-size:46px;"></a>
    <a href="https://github.com/shamindras" target="_blank" class="fa fa-github"  style="font-size:36px;"></a>
</p>

## Acknowledgments {.appendix}

I'd like to thank Salil Shrotriya for taking my profile
pic which is the preview image for this post. 