---
title: "Shamindra's July 2019 Roundup"
description: |
  A quick roundup of any interesting July 2019
  activities
author:
  - name: Shamindra Shrotriya
    url: https://www.shamindras.com/
date: 07-31-2019
slug: shrotriya2019july19rndup
draft: true
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
bibliography: ../../refs.bib    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction

This is a new feature I'm going to experiment with, namely documenting
anything interesting I come across (articles, lectures, books, papers
etc.) and any activities I get up to. This is more for my personal
benefit but may also help others. Let's see how this experiment goes!

## Interesting Articles

- Came across this [exhaustive `BibTex` example file](http://mirrors.concertpass.com/tex-archive/biblio/bibtex/base/xampl.bib) 
which will be a really handy reference going forward for $\LaTeX$ documents

- This [Pimp my RMD: a few tips for R Markdown](https://holtzy.github.io/Pimp-my-rmd/#highlight_a_piece_of_text) document is a very good site to help deal with really slick 
features of editing `Rmd` documents. 
  - One nice feature I noticed was to use `HTML` to center
  an image per [here](https://holtzy.github.io/Pimp-my-rmd/#center_an_image)

## Interesting Books

### Non-fiction

- Continued reading this fantastic book [@steele2004cauchyscwarzmaster_book] on the Art of Mathematical inequalities by [Prof. Michael Steele](http://www-stat.wharton.upenn.edu/~steele/). This book is simply
amazing in that Prof. Steele walks through deriving mathematical 
inequalities as if you were having a chat with a whiteboard. I'll be working through the problems in detail (the text contains full
solutions for self-study). Who knows perhaps I'll blog about it in the future.

### Fiction

- Read Celeste Ng's [Everything I Never Told You](https://www.celesteng.com/everything-i-never-told-you). Very nicely
written debut novel by Ng, though quite dark and brooding in tone. Would
not recommend as a pick me up but certainly would for a nice American-Asian character study set in the 1970s.

## Interesting Papers

- Enjoyed reading this paper on the mathematical description of the carbon cycle
[@rothman14_earth_carbon_cycle]
  <details><summary>Key Points</summary>
  <p>
  - I enjoyed
  </p>
  </details>
  
## Personal Blogging Front

Besides this post `r emo::ji("smile")` the main things I got up to
on the personal blogging from were:

- Setting up this very blog, with a [detailed step-by-step guide](https://www.shamindras.com/posts/2019-07-11-setting-up-a-distill-blog-with-netlify/) on the fun setup process with the [RStudio distill package](https://rstudio.github.io/distill/blog.html) and
also [Netlify](https://netlify.com) and [Google Domains](https://domains.google)
- Wrote a [fun blogpost](https://www.shamindras.com/posts/2019-07-15-shrotriya2019tidyfunpt1/) on solving a couple of quick text-based tasks
using the `tidyverse` including [generating Oxford Comma triples](https://www.shamindras.com/posts/2019-07-15-shrotriya2019tidyfunpt1/#task-1-generating-oxford-comma-triples) and also [Generating numbered BibTeX entries](https://www.shamindras.com/posts/2019-07-15-shrotriya2019tidyfunpt1/#task-2-generating-numbered-bibtex-entries)
